config/routes.rb
Rails.application.routes.draw do
  resources :member_visits
  resources :customer_leads
  resources :stocks
  resources :products
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
end

app/models/customer_lead.rb
class CustomerLead < ApplicationRecord
end

app/controllers/customer_leads_controller.rb
class CustomerLeadsController < ApplicationController
  before_action :set_customer_lead, only: [:show, :edit, :update, :destroy]

  # GET /customer_leads
  # GET /customer_leads.json
  def index
    @customer_leads = CustomerLead.all
  end

  # GET /customer_leads/1
  # GET /customer_leads/1.json
  def show
  end

  # GET /customer_leads/new
  def new
    @customer_lead = CustomerLead.new
  end

  # GET /customer_leads/1/edit
  def edit
  end

  # POST /customer_leads
  # POST /customer_leads.json
  def create
    @customer_lead = CustomerLead.new(customer_lead_params)

    respond_to do |format|
      if @customer_lead.save
        format.html { redirect_to @customer_lead, notice: 'Customer lead was successfully created.' }
        format.json { render :show, status: :created, location: @customer_lead }
      else
        format.html { render :new }
        format.json { render json: @customer_lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_leads/1
  # PATCH/PUT /customer_leads/1.json
  def update
    respond_to do |format|
      if @customer_lead.update(customer_lead_params)
        format.html { redirect_to @customer_lead, notice: 'Customer lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_lead }
      else
        format.html { render :edit }
        format.json { render json: @customer_lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_leads/1
  # DELETE /customer_leads/1.json
  def destroy
    @customer_lead.destroy
    respond_to do |format|
      format.html { redirect_to customer_leads_url, notice: 'Customer lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_lead
      @customer_lead = CustomerLead.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_lead_params
      params.require(:customer_lead).permit(:name, :phone, :height_cm, :weight_kg)
    end
end

app/helpers/customer_leads_helper.rb
module CustomerLeadsHelper
end

app/views/customer_leads/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= simple_form_for(@customer_lead) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <%= f.input :id, disabled: true %>
      <%= f.input :name %>
      <%= f.input :phone %>
      <%= f.input :complimentary_shake, as: :select, :selected => f.object.complimentary_shake || "false" %>
      <%= f.input :height_cm %>
      <%= f.input :weight_kg %>

      <%= f.button :submit, class: "btn-primary" %>
      <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
    <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/customer_leads/edit.html.erb
<h1>Editing Customer Lead</h1>

<%= render 'form', customer_lead: @customer_lead %>

app/views/customer_leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Leads</h1>

<%= link_to 'New Lead', new_customer_lead_path, :class => 'btn btn-primary' %>

<table  class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @customer_leads.each do |customer_lead| %>
      <tr>
        <th scope="col"><%= customer_lead.id %></th>
        <td><%= customer_lead.name %></td>
        <td><%= customer_lead.phone %></td>
        <td>
          <div>
            <%= link_to 'Show', customer_lead, :class => 'btn btn-primary' %>
            <%= link_to 'Edit', edit_customer_lead_path(customer_lead), :class => 'btn btn-default' %>
            <%= link_to 'Delete', customer_lead, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/customer_leads/new.html.erb
<h1>New Customer Lead</h1>

<%= render 'form', customer_lead: @customer_lead %>

app/views/customer_leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @customer_lead.id %>
</p>


<p>
  <strong>Name:</strong>
  <%= @customer_lead.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer_lead.phone %>
</p>

<p>
  <strong>Height cm:</strong>
  <%= @customer_lead.height_cm %>
</p>

<p>
  <strong>Weight kg:</strong>
  <%= @customer_lead.weight_kg %>
</p>

<%= link_to 'Edit', edit_customer_lead_path(@customer_lead), {:class=>"btn btn-primary"} %>
<%= link_to "View All", customer_leads_path, {:class=>"btn btn-default"} %>