config/routes.rb
Rails.application.routes.draw do
  resources :member_visits
  resources :customer_leads
  resources :stocks
  resources :products
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
end

app/views/layouts/_navbar.html.erb
<div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Nandita', root_path, :class => 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Stocks', stocks_path %></li>
            </ul>
          </li>
          <li><%= link_to 'Members', members_path %></li>
          <li><%= link_to 'Leads', customer_leads_path %></li>
          <li><%= link_to 'Add Member Visit', new_member_visit_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NanditaNutritionClub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar', :formats => [:html] %>
      <%= yield %>
    </div>
  </body>
  <script>
      $(document).ready(function() {
          $('.select.select2 select').select2();
      });
  </script>
</html>